# Aluno: Tiago - Número: 122991
name: Qodana - God Class Detection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.2
        with:
          args: --linter,jetbrains/qodana-jvm
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} # Se usar a versão Cloud