
name: SonarQube Cloud Analysis

on:
  push:
    branches: [ "main" ] # Analisa o projeto quando fazes push na main
  pull_request:
    branches: [ "main" ]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Importante para o SonarQube ter o histórico completo
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token automático do GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # O token que acabaste de criar
